spring:
  application:
    name: backend

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADD}
    password: ${GMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

langchain4j:
  open-ai:
    api-key: ${GITHUB_KEY}
    base-url: https://models.inference.ai.azure.com
    chat-model:
      model-name: gpt-4o
      temperature: 0.7
    embedding-model:
      model-name: text-embedding-3-small

ai:
  pgvector:
    host: ep-wandering-bar-a1moigem-pooler.ap-southeast-1.aws.neon.tech
    port: 5432
    database: ai_service
    table: embeddings
    dimension: 1536

aws:
  s3:
    bucket-name: infrastrack
    region: us-east-1
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

  cognito:
    userPoolId: ${USER_POOL_ID}
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    region: us-east-1

mail:
  imap:
    host: imap.gmail.com
    port: 993
    username: ${GMAIL_ADD}
    password: ${GMAIL_PASS}

server:
  port: 8081